apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "components.fullname" "ui"}}
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/component: {{ include "components.fullname" "ui"}}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flame
      app.kubernetes.io/component: {{ include "components.fullname" "ui"}}
      app.kubernetes.io/version: {{ .Chart.AppVersion }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flame
        app.kubernetes.io/component: {{ include "components.fullname" "ui"}}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: node-ui
          {{ if eq .Values.env "production" }}
          image: ghcr.io/privateaim/node-ui:prod
          {{ else }}
          image: ghcr.io/privateaim/node-ui:latest
          {{ end }}
          imagePullPolicy: Always  # Maybe "Always" during debug
          ports:
            - containerPort: 3000
              name: ui
          env:
            - name: NODE_ENV
              value: {{ .Values.env | default "production" | quote }}
            - name: NUXT_PUBLIC_BASE_URL
              value: {{ include "ui.ingress.hostname" . }}
            - name: NUXT_PUBLIC_HUB_ADAPTER_URL
              value: {{ include "ui.adapter.endpoint" . }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_REDIRECT_URI
              value: {{ printf "%s/auth/keycloak/callback" (include "ui.ingress.hostname" .) }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_AUTHORIZATION_URL
              value: {{ printf "%s/protocol/openid-connect/auth" (include "ui.keycloak.frontend.endpoint" .) }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_TOKEN_URL
              value: {{ printf "%s/protocol/openid-connect/token" (include "ui.keycloak.service.endpoint" .) }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_USERINFO_URL
              value: {{ printf "%s/protocol/openid-connect/userinfo" (include "ui.keycloak.service.endpoint" .) }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID
              value: {{ .Values.idp.clientId | default "node-ui" | quote }}
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ui.keycloak.secretName" . }}
                  key: {{ include "ui.keycloak.secretKey" . }}
            - name: NUXT_OIDC_TOKEN_KEY
              value: {{ randAlphaNum 32 | b64enc }}
            - name: NUXT_OIDC_SESSION_SECRET
              value: {{ randAlphaNum 48 | quote }}
            - name: NUXT_OIDC_AUTH_SESSION_SECRET
              value: {{ randAlphaNum 48 | quote }}